import "./globals.css";
import { Roboto } from "next/font/google";
import Navbar from "@/components/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// const inter = Inter({ subsets: ["latin"] });

const roboto = Roboto({
  subsets: ["latin"],
  weight: "400",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={roboto.className}>
      <body className="min-h-screen flex flex-col">
        <Navbar />
        <div className="w-full flex-grow pt-16 bg-zinc-900">{children}</div>
      </body>
    </html>
  );
}
